# Generated by Django 5.1.15 on 2026-08-16 07:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0001_initial'),
        ('targets', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asset_type', models.CharField(choices=[('DOMAIN', 'DOMAIN'), ('IP', 'IP'), ('SUBDOMAIN', 'SUBDOMAIN'), ('HOST', 'HOST'), ('URL', 'URL'), ('API', 'API')], max_length=20)),
                ('value', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('SAFE', 'SAFE'), ('WARNING', 'WARNING'), ('COMPROMISED', 'COMPROMISED')], default='SAFE', max_length=20)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('discovered_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assets', to='projects.project')),
                ('target', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assets', to='targets.target')),
            ],
        ),
    ]
