# Generated by Django 5.1.15 on 2026-08-16 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='asset_type',
            field=models.CharField(choices=[('DOMAIN', 'DOMAIN'), ('IP', 'IP'), ('SUBDOMAIN', 'SUBDOMAIN'), ('HOST', 'HOST'), ('URL', 'URL'), ('API', 'API'), ('PORT', 'PORT'), ('SERVICE', 'SERVICE')], max_length=20),
        ),
    ]
