# Generated by Django 5.1.15 on 2026-08-16 07:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Scan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('scan_type', models.CharField(choices=[('RECON', 'RECON'), ('NETWORK', 'NETWORK'), ('WEB', 'WEB'), ('API', 'API'), ('CODE', 'CODE'), ('FULL', 'FULL')], max_length=20)),
                ('status', models.CharField(choices=[('QUEUED', 'QUEUED'), ('RUNNING', 'RUNNING'), ('COMPLETED', 'COMPLETED'), ('FAILED', 'FAILED'), ('CANCELLED', 'CANCELLED')], default='QUEUED', max_length=20)),
                ('progress', models.IntegerField(default=0)),
                ('configuration', models.JSONField(blank=True, default=dict)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scans', to='projects.project')),
            ],
        ),
    ]
