# Generated by Django 5.1.15 on 2026-08-16 07:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Target',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('target_type', models.CharField(choices=[('DOMAIN', 'DOMAIN'), ('IP', 'IP'), ('CIDR', 'CIDR'), ('URL', 'URL'), ('API', 'API'), ('REPOSITORY', 'REPOSITORY')], max_length=20)),
                ('value', models.CharField(max_length=255)),
                ('environment', models.CharField(choices=[('LIVE', 'LIVE'), ('STAGING', 'STAGING'), ('DEVELOPMENT', 'DEVELOPMENT'), ('LOCAL', 'LOCAL')], max_length=20)),
                ('scope', models.BooleanField(default=True)),
                ('status', models.CharField(choices=[('ACTIVE', 'ACTIVE'), ('INACTIVE', 'INACTIVE')], default='ACTIVE', max_length=20)),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='targets', to='projects.project')),
            ],
        ),
    ]
