# Generated by Django 5.1.15 on 2026-08-16 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TestingModule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=100, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, default='')),
                ('category', models.CharField(max_length=50)),
                ('version', models.CharField(default='1.0.0', max_length=20)),
                ('enabled', models.BooleanField(default=True)),
                ('requires_live_url', models.BooleanField(default=False)),
                ('requires_source_code', models.BooleanField(default=False)),
                ('requires_authentication', models.BooleanField(default=False)),
                ('supports_live_testing', models.BooleanField(default=True)),
                ('supports_local_testing', models.BooleanField(default=True)),
                ('configuration_schema', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
