from django.db import migrations

def seed_modules(apps, schema_editor):
    TestingModule = apps.get_model('core', 'TestingModule')
    
    modules = [
        # RECONNAISSANCE
        {
            'key': 'asset_discovery',
            'name': 'Asset Discovery',
            'category': 'RECON',
            'description': 'Discovers public assets, subdomains, and related targets belonging to the scope.',
            'requires_live_url': True,
            'requires_source_code': False,
            'requires_authentication': False,
        },
        {
            'key': 'dns_assessment',
            'name': 'DNS Assessment',
            'category': 'RECON',
            'description': 'Analyzes DNS configurations, records, security parameters, and zone details.',
            'requires_live_url': True,
            'requires_source_code': False,
            'requires_authentication': False,
        },
        {
            'key': 'subdomain_discovery',
            'name': 'Subdomain Discovery',
            'category': 'RECON',
            'description': 'Discovers passive and active subdomains for target domains.',
            'requires_live_url': True,
            'requires_source_code': False,
            'requires_authentication': False,
        },
        {
            'key': 'service_discovery',
            'name': 'Service Discovery',
            'category': 'RECON',
            'description': 'Scans and identifies active network services running on target ports.',
            'requires_live_url': True,
            'requires_source_code': False,
            'requires_authentication': False,
        },
        {
            'key': 'technology_detection',
            'name': 'Technology Detection',
            'category': 'RECON',
            'description': 'Identifies web frameworks, CMSs, language backends, and server versions.',
            'requires_live_url': True,
            'requires_source_code': False,
            'requires_authentication': False,
        },
        {
            'key': 'tls_ssl_assessment',
            'name': 'TLS/SSL Assessment',
            'category': 'RECON',
            'description': 'Analyzes certificate validities, cipher suites, vulnerabilities, and TLS versions.',
            'requires_live_url': True,
            'requires_source_code': False,
            'requires_authentication': False,
        },

        # NETWORK SECURITY
        {
            'key': 'network_exposure',
            'name': 'Network Exposure Assessment',
            'category': 'NETWORK',
            'description': 'Identifies public-facing networking devices and edge systems.',
            'requires_live_url': True,
            'requires_source_code': False,
            'requires_authentication': False,
        },
        {
            'key': 'port_service_assessment',
            'name': 'Port and Service Assessment',
            'category': 'NETWORK',
            'description': 'Detailed configuration audits on open network ports.',
            'requires_live_url': True,
            'requires_source_code': False,
            'requires_authentication': False,
        },
        {
            'key': 'network_config_assessment',
            'name': 'Network Configuration Assessment',
            'category': 'NETWORK',
            'description': 'Audits firewall setups and network routing protocols.',
            'requires_live_url': True,
            'requires_source_code': False,
            'requires_authentication': False,
        },

        # WEB APPLICATION SECURITY
        {
            'key': 'web_app_discovery',
            'name': 'Web Application Discovery',
            'category': 'WEB',
            'description': 'Maps target paths, subfolders, configurations, and structures.',
            'requires_live_url': True,
            'requires_source_code': False,
            'requires_authentication': False,
        },
        {
            'key': 'http_security_analysis',
            'name': 'HTTP Security Analysis',
            'category': 'WEB',
            'description': 'Audits HTTP transport methods, TLS redirection, and verb exposure.',
            'requires_live_url': True,
            'requires_source_code': False,
            'requires_authentication': False,
        },
        {
            'key': 'web_security_headers',
            'name': 'Security Headers',
            'category': 'WEB',
            'description': 'Checks for presence and configuration of security headers (CSP, HSTS, CORS, etc.).',
            'requires_live_url': True,
            'requires_source_code': False,
            'requires_authentication': False,
        },
        {
            'key': 'cookie_session_security',
            'name': 'Cookie/Sessions Security',
            'category': 'WEB',
            'description': 'Audits cookie flags like Secure, HttpOnly, and SameSite.',
            'requires_live_url': True,
            'requires_source_code': False,
            'requires_authentication': False,
        },
        {
            'key': 'auth_security_assessment',
            'name': 'Authentication Security Assessment',
            'category': 'WEB',
            'description': 'Identifies flaws in login, registration, password policy, and auth schemes.',
            'requires_live_url': True,
            'requires_source_code': False,
            'requires_authentication': False,
        },
        {
            'key': 'authz_access_control',
            'name': 'Authorization/Access-Control Assessment',
            'category': 'WEB',
            'description': 'Checks privileges escalation patterns and access management bypass.',
            'requires_live_url': True,
            'requires_source_code': False,
            'requires_authentication': False,
        },
        {
            'key': 'input_validation',
            'name': 'Input Validation Assessment',
            'category': 'WEB',
            'description': 'Audits form fields and endpoints for XSS, SQLi, and Command Injection.',
            'requires_live_url': True,
            'requires_source_code': False,
            'requires_authentication': False,
        },
        {
            'key': 'file_upload_security',
            'name': 'File Upload Security Assessment',
            'category': 'WEB',
            'description': 'Validates checks on upload extensions, size, and paths.',
            'requires_live_url': True,
            'requires_source_code': False,
            'requires_authentication': False,
        },
        {
            'key': 'error_info_disclosure',
            'name': 'Error and Information Disclosure',
            'category': 'WEB',
            'description': 'Finds debug information, stack traces, and verbose error messages.',
            'requires_live_url': True,
            'requires_source_code': False,
            'requires_authentication': False,
        },
        {
            'key': 'configuration_exposure',
            'name': 'Configuration Exposure',
            'category': 'WEB',
            'description': 'Finds backup, environmental configuration, and standard system paths exposed.',
            'requires_live_url': True,
            'requires_source_code': False,
            'requires_authentication': False,
        },
        {
            'key': 'content_endpoint_discovery',
            'name': 'Content/Endpoint Discovery',
            'category': 'WEB',
            'description': 'Fuzzes web server endpoints for hidden routes and administrative interfaces.',
            'requires_live_url': True,
            'requires_source_code': False,
            'requires_authentication': False,
        },

        # API SECURITY
        {
            'key': 'api_discovery',
            'name': 'API Discovery',
            'category': 'API',
            'description': 'Finds REST, SOAP, GraphQL, and RPC APIs and directories.',
            'requires_live_url': True,
            'requires_source_code': False,
            'requires_authentication': False,
        },
        {
            'key': 'openapi_swagger_analysis',
            'name': 'OpenAPI/Swagger Analysis',
            'category': 'API',
            'description': 'Audits OpenAPI definitions for undocumented routes and schema discrepancies.',
            'requires_live_url': True,
            'requires_source_code': False,
            'requires_authentication': False,
        },
        {
            'key': 'api_auth_assessment',
            'name': 'API Authentication Assessment',
            'category': 'API',
            'description': 'Validates API token management, key authorization, and validation schemas.',
            'requires_live_url': True,
            'requires_source_code': False,
            'requires_authentication': False,
        },
        {
            'key': 'api_authz_assessment',
            'name': 'API Authorization Assessment',
            'category': 'API',
            'description': 'Checks APIs for IDOR, BOLA, and privilege containment.',
            'requires_live_url': True,
            'requires_source_code': False,
            'requires_authentication': False,
        },
        {
            'key': 'api_input_validation',
            'name': 'API Input Validation',
            'category': 'API',
            'description': 'Audits API requests for payload parsing flaws and command schemas.',
            'requires_live_url': True,
            'requires_source_code': False,
            'requires_authentication': False,
        },
        {
            'key': 'api_config_security',
            'name': 'API Configuration Security',
            'category': 'API',
            'description': 'Checks CORS configurations, HTTP security verbs, and response parsing.',
            'requires_live_url': True,
            'requires_source_code': False,
            'requires_authentication': False,
        },
        {
            'key': 'api_rate_limit',
            'name': 'Rate-Limit Assessment',
            'category': 'API',
            'description': 'Checks API endpoint resilience to DDoS, request bursts, and resource exhaustion.',
            'requires_live_url': True,
            'requires_source_code': False,
            'requires_authentication': False,
        },
        {
            'key': 'api_data_exposure',
            'name': 'Data Exposure Assessment',
            'category': 'API',
            'description': 'Identifies over-shared fields, PI exposure, and verbose metadata in JSON formats.',
            'requires_live_url': True,
            'requires_source_code': False,
            'requires_authentication': False,
        },
        {
            'key': 'api_cors_assessment',
            'name': 'CORS Assessment',
            'category': 'API',
            'description': 'Finds lax and wildcard CORS credentials permissions on secure API endpoints.',
            'requires_live_url': True,
            'requires_source_code': False,
            'requires_authentication': False,
        },
        {
            'key': 'api_jwt_security',
            'name': 'JWT Security Assessment',
            'category': 'API',
            'description': 'Finds weak cryptographic keys, algorithm confusions, and verification bypasses.',
            'requires_live_url': True,
            'requires_source_code': False,
            'requires_authentication': False,
        },
        {
            'key': 'api_graphql_security',
            'name': 'GraphQL Security Assessment',
            'category': 'API',
            'description': 'Audits GraphQL setups for query complexity, introspection status, and nested requests.',
            'requires_live_url': True,
            'requires_source_code': False,
            'requires_authentication': False,
        },

        # SOURCE CODE SECURITY
        {
            'key': 'sast',
            'name': 'SAST',
            'category': 'CODE',
            'description': 'Static Application Security Testing on the source code.',
            'requires_live_url': False,
            'requires_source_code': True,
            'requires_authentication': False,
        },
        {
            'key': 'secret_detection',
            'name': 'Secret Detection',
            'category': 'CODE',
            'description': 'Scans repository code for hardcoded passwords, tokens, API keys, and certificates.',
            'requires_live_url': False,
            'requires_source_code': True,
            'requires_authentication': False,
        },
        {
            'key': 'dependency_analysis',
            'name': 'Dependency Analysis',
            'category': 'CODE',
            'description': 'Audits third-party code libraries for known vulnerabilities.',
            'requires_live_url': False,
            'requires_source_code': True,
            'requires_authentication': False,
        },
        {
            'key': 'configuration_analysis',
            'name': 'Configuration Analysis',
            'category': 'CODE',
            'description': 'Scans web server configurations, compose scripts, and infrastructure files.',
            'requires_live_url': False,
            'requires_source_code': True,
            'requires_authentication': False,
        },
        {
            'key': 'auth_code_review',
            'name': 'Authentication Code Review',
            'category': 'CODE',
            'description': 'Reviews internal auth logic, crypto storage structures, and hashing.',
            'requires_live_url': False,
            'requires_source_code': True,
            'requires_authentication': False,
        },
        {
            'key': 'authz_code_review',
            'name': 'Authorization Code Review',
            'category': 'CODE',
            'description': 'Validates middleware logic, path exclusions, and role mappings in code.',
            'requires_live_url': False,
            'requires_source_code': True,
            'requires_authentication': False,
        },
        {
            'key': 'injection_pattern',
            'name': 'Injection Pattern Detection',
            'category': 'CODE',
            'description': 'Locates direct DB queries, raw string concatenations, and templating execution.',
            'requires_live_url': False,
            'requires_source_code': True,
            'requires_authentication': False,
        },
        {
            'key': 'unsafe_file_command',
            'name': 'Unsafe File/Command Handling',
            'category': 'CODE',
            'description': 'Finds eval, spawn commands, OS directory integrations, and temp file creation.',
            'requires_live_url': False,
            'requires_source_code': True,
            'requires_authentication': False,
        },
        {
            'key': 'crypto_usage_analysis',
            'name': 'Cryptography Usage Analysis',
            'category': 'CODE',
            'description': 'Identifies broken cipher configurations, MD5/SHA1 usage, and hardcoded salts.',
            'requires_live_url': False,
            'requires_source_code': True,
            'requires_authentication': False,
        },
        {
            'key': 'error_handling_analysis',
            'name': 'Error Handling Analysis',
            'category': 'CODE',
            'description': 'Checks for empty catch statements, leakage of diagnostic variables, and crash bugs.',
            'requires_live_url': False,
            'requires_source_code': True,
            'requires_authentication': False,
        },

        # SUPPLY CHAIN
        {
            'key': 'dependency_vulnerability',
            'name': 'Dependency Vulnerability Analysis',
            'category': 'SUPPLY_CHAIN',
            'description': 'Audits target software requirements against current vulnerability databases.',
            'requires_live_url': False,
            'requires_source_code': True,
            'requires_authentication': False,
        },
        {
            'key': 'lockfile_analysis',
            'name': 'Lockfile Analysis',
            'category': 'SUPPLY_CHAIN',
            'description': 'Analyzes integrity hashes and resolves dependencies trees in npm, pip, yarn lockfiles.',
            'requires_live_url': False,
            'requires_source_code': True,
            'requires_authentication': False,
        },
        {
            'key': 'container_config',
            'name': 'Container Configuration Analysis',
            'category': 'SUPPLY_CHAIN',
            'description': 'Audits Dockerfile configurations and container configurations.',
            'requires_live_url': False,
            'requires_source_code': True,
            'requires_authentication': False,
        },
        {
            'key': 'iac_analysis',
            'name': 'Infrastructure-as-Code Analysis',
            'category': 'SUPPLY_CHAIN',
            'description': 'Scans Terraform, CloudFormation, and Kubernetes manifests for structural errors.',
            'requires_live_url': False,
            'requires_source_code': True,
            'requires_authentication': False,
        },

        # EXPOSURE / INTELLIGENCE
        {
            'key': 'public_asset_exposure',
            'name': 'Public Asset Exposure',
            'category': 'EXPOSURE',
            'description': 'Identifies misconfigured domain records, subdomains takeover, and cloud storage leaks.',
            'requires_live_url': True,
            'requires_source_code': False,
            'requires_authentication': False,
        },
        {
            'key': 'certificate_intelligence',
            'name': 'Certificate Intelligence',
            'category': 'EXPOSURE',
            'description': 'Gathers metadata and targets from certificate transparency logs.',
            'requires_live_url': True,
            'requires_source_code': False,
            'requires_authentication': False,
        },
        {
            'key': 'public_repo_exposure',
            'name': 'Public Repository Exposure',
            'category': 'EXPOSURE',
            'description': 'Scans public OSINT sources for leakage of target source files or git targets.',
            'requires_live_url': True,
            'requires_source_code': False,
            'requires_authentication': False,
        },
        {
            'key': 'public_config_exposure',
            'name': 'Public Configuration Exposure',
            'category': 'EXPOSURE',
            'description': 'Finds administrative, metrics, or server configs exposed on external networks.',
            'requires_live_url': True,
            'requires_source_code': False,
            'requires_authentication': False,
        },
    ]
    
    for mod in modules:
        TestingModule.objects.update_or_create(key=mod['key'], defaults=mod)

class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(seed_modules),
    ]
