# Generated by Django 5.1.15 on 2026-08-16 07:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('assets', '0001_initial'),
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Finding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, default='')),
                ('severity', models.CharField(choices=[('CRITICAL', 'CRITICAL'), ('HIGH', 'HIGH'), ('MEDIUM', 'MEDIUM'), ('LOW', 'LOW'), ('INFO', 'INFO')], max_length=20)),
                ('status', models.CharField(choices=[('OPEN', 'OPEN'), ('CONFIRMED', 'CONFIRMED'), ('FALSE_POSITIVE', 'FALSE_POSITIVE'), ('ACCEPTED_RISK', 'ACCEPTED_RISK'), ('RESOLVED', 'RESOLVED')], default='OPEN', max_length=20)),
                ('cvss_score', models.DecimalField(decimal_places=1, default=0.0, max_digits=3)),
                ('cwe', models.CharField(blank=True, default='', max_length=50)),
                ('evidence', models.TextField(blank=True, default='')),
                ('remediation', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('asset', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='findings', to='assets.asset')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='findings', to='projects.project')),
            ],
        ),
    ]
