# Generated by Django 5.1.15 on 2026-08-16 11:02

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_seed_testing_modules'),
        ('findings', '0001_initial'),
        ('projects', '0002_project_live_url_project_source_archive_and_more'),
        ('scans', '0002_scanjob_moduleexecution_executionlog'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='finding',
            name='evidence',
        ),
        migrations.AddField(
            model_name='finding',
            name='assessment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='findings', to='projects.assessment'),
        ),
        migrations.AddField(
            model_name='finding',
            name='category',
            field=models.CharField(choices=[('NETWORK', 'NETWORK'), ('WEB', 'WEB'), ('API', 'API'), ('AUTHENTICATION', 'AUTHENTICATION'), ('AUTHORIZATION', 'AUTHORIZATION'), ('CONFIGURATION', 'CONFIGURATION'), ('CRYPTOGRAPHY', 'CRYPTOGRAPHY'), ('INJECTION', 'INJECTION'), ('DISCLOSURE', 'DISCLOSURE'), ('SECRETS', 'SECRETS'), ('DEPENDENCY', 'DEPENDENCY'), ('SOURCE_CODE', 'SOURCE_CODE'), ('TLS', 'TLS'), ('OSINT', 'OSINT'), ('OTHER', 'OTHER')], default='OTHER', max_length=50),
        ),
        migrations.AddField(
            model_name='finding',
            name='confidence',
            field=models.CharField(choices=[('CONFIRMED', 'CONFIRMED'), ('HIGH', 'HIGH'), ('MEDIUM', 'MEDIUM'), ('LOW', 'LOW')], default='MEDIUM', max_length=20),
        ),
        migrations.AddField(
            model_name='finding',
            name='fingerprint',
            field=models.CharField(blank=True, db_index=True, max_length=64, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='finding',
            name='metadata',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='finding',
            name='references',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='finding',
            name='scan_job',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='findings', to='scans.scanjob'),
        ),
        migrations.AddField(
            model_name='finding',
            name='testing_module',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='findings', to='core.testingmodule'),
        ),
        migrations.AlterField(
            model_name='finding',
            name='cvss_score',
            field=models.DecimalField(decimal_places=1, default=0.0, max_digits=3, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(10.0)]),
        ),
        migrations.AlterField(
            model_name='finding',
            name='severity',
            field=models.CharField(choices=[('CRITICAL', 'CRITICAL'), ('HIGH', 'HIGH'), ('MEDIUM', 'MEDIUM'), ('LOW', 'LOW'), ('INFO', 'INFO')], default='INFO', max_length=20),
        ),
        migrations.CreateModel(
            name='FindingEvidence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('evidence_type', models.CharField(choices=[('HTTP_REQUEST', 'HTTP_REQUEST'), ('HTTP_RESPONSE', 'HTTP_RESPONSE'), ('NETWORK', 'NETWORK'), ('SOURCE_CODE', 'SOURCE_CODE'), ('CONFIGURATION', 'CONFIGURATION'), ('COMMAND_OUTPUT', 'COMMAND_OUTPUT'), ('SCREENSHOT', 'SCREENSHOT'), ('TEXT', 'TEXT'), ('OTHER', 'OTHER')], default='OTHER', max_length=30)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, default='')),
                ('request', models.JSONField(blank=True, default=dict)),
                ('response', models.JSONField(blank=True, default=dict)),
                ('location', models.TextField(blank=True, default='')),
                ('payload', models.TextField(blank=True, default='')),
                ('code_snippet', models.TextField(blank=True, default='')),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('finding', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evidence_records', to='findings.finding')),
            ],
        ),
        migrations.CreateModel(
            name='FindingOccurrence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_seen', models.DateTimeField(auto_now_add=True)),
                ('last_seen', models.DateTimeField(auto_now=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('finding', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='occurrences', to='findings.finding')),
                ('scan_job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='finding_occurrences', to='scans.scanjob')),
            ],
        ),
    ]
