# Generated by Django 5.1.15 on 2026-09-13 12:24

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UnifiedScanRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('target', models.CharField(help_text='Target URL, hostname, or IP address', max_length=512)),
                ('cleaned_target', models.CharField(blank=True, default='', max_length=256)),
                ('resolved_ip', models.CharField(blank=True, default='', max_length=128)),
                ('codebase_source_type', models.CharField(default='path', help_text="'path' or 'zip'", max_length=32)),
                ('codebase_path', models.CharField(blank=True, default='', max_length=1024)),
                ('codebase_zip_name', models.CharField(blank=True, default='', max_length=256)),
                ('scan_profile', models.CharField(choices=[('quick', 'Quick Recon'), ('standard', 'Standard Balanced'), ('deep', 'Deep Pentest')], default='standard', max_length=32)),
                ('intensity', models.CharField(choices=[('low', 'Low'), ('normal', 'Normal'), ('aggressive', 'Aggressive')], default='normal', max_length=32)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('RUNNING', 'Running'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed'), ('ABORTED', 'Aborted')], db_index=True, default='PENDING', max_length=32)),
                ('progress_percent', models.IntegerField(default=0)),
                ('current_module_id', models.CharField(blank=True, default='', max_length=64)),
                ('overall_score', models.IntegerField(default=100)),
                ('score_grade', models.CharField(default='A', max_length=8)),
                ('risk_rating', models.CharField(default='Low Risk', max_length=64)),
                ('active_modules', models.JSONField(default=list, help_text='List of active module IDs requested')),
                ('findings_summary', models.JSONField(default=dict, help_text='Count of critical, high, medium, low, info findings')),
                ('module_statuses', models.JSONField(default=dict, help_text='Per-module execution state (pending, running, completed, failed, duration, steps)')),
                ('module_results', models.JSONField(default=dict, help_text='Full results dictionary returned by each module')),
                ('findings', models.JSONField(default=list, help_text='Aggregated and standardized list of security findings')),
                ('logs', models.JSONField(default=list, help_text='Ordered log entries emitted during orchestration')),
                ('error_message', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Unified Scan Record',
                'verbose_name_plural': 'Unified Scan Records',
                'ordering': ['-created_at'],
            },
        ),
    ]
