# Generated by Django 5.1.15 on 2026-09-13 12:53

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unified_scan', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Finding',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(db_index=True, max_length=256)),
                ('description', models.TextField()),
                ('severity', models.CharField(choices=[('critical', 'Critical'), ('high', 'High'), ('medium', 'Medium'), ('low', 'Low'), ('info', 'Informational')], db_index=True, default='medium', max_length=32)),
                ('confidence', models.CharField(choices=[('certain', 'Certain'), ('firm', 'Firm'), ('tentative', 'Tentative')], default='firm', max_length=32)),
                ('cvss_score', models.FloatField(default=0.0)),
                ('cwe', models.CharField(blank=True, db_index=True, default='', max_length=64)),
                ('source_module', models.CharField(choices=[('ports', 'Port & Network Discovery'), ('http', 'HTTP Detection & Header Audit'), ('endpoints', 'Endpoint & Route Discovery'), ('attack-surface', 'Web Application & Form Analysis'), ('fingerprint', 'Technology Fingerprinting'), ('tls', 'TLS / SSL Security Analysis'), ('security-config', 'Security Configuration Audit'), ('api-analysis', 'API Security & Deep Analysis'), ('codebase-analysis', 'Codebase Security (SAST & Secrets)')], db_index=True, max_length=64)),
                ('source_module_name', models.CharField(blank=True, default='', max_length=128)),
                ('target', models.CharField(db_index=True, help_text='Target host, URL, IP or repo', max_length=512)),
                ('location', models.CharField(blank=True, default='', help_text='Specific asset/endpoint/file/port', max_length=512)),
                ('evidence', models.JSONField(default=dict, help_text='Structured proof, banners, or code context')),
                ('request_data', models.TextField(blank=True, default='')),
                ('response_data', models.TextField(blank=True, default='')),
                ('remediation', models.TextField(blank=True, default='')),
                ('references', models.JSONField(default=list, help_text='List of reference URLs (CVE, OWASP, CWE)')),
                ('status', models.CharField(choices=[('open', 'Open'), ('confirmed', 'Confirmed'), ('remediated', 'Remediated'), ('accepted', 'Accepted Risk'), ('false_positive', 'False Positive')], db_index=True, default='open', max_length=32)),
                ('status_note', models.TextField(blank=True, default='')),
                ('fingerprint_hash', models.CharField(db_index=True, max_length=64, unique=True)),
                ('occurrence_count', models.IntegerField(default=1)),
                ('first_seen', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('last_seen', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('scan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scan_findings', to='unified_scan.unifiedscanrecord')),
            ],
            options={
                'verbose_name': 'Security Finding',
                'verbose_name_plural': 'Security Findings',
                'ordering': ['-last_seen', '-cvss_score'],
            },
        ),
    ]
