# Generated by Django 5.1.15 on 2026-09-13 13:47

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unified_scan', '0002_finding'),
    ]

    operations = [
        migrations.CreateModel(
            name='SecurityReport',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(db_index=True, max_length=256)),
                ('report_type', models.CharField(choices=[('executive', 'Executive Summary'), ('technical', 'Technical Pentest Audit'), ('attack_surface', 'Attack Surface & Perimeter'), ('full_audit', 'Full Security Assessment')], db_index=True, default='executive', max_length=32)),
                ('format', models.CharField(choices=[('pdf', 'PDF Document'), ('html', 'HTML Interactive'), ('json', 'JSON Export')], default='pdf', max_length=16)),
                ('target', models.CharField(db_index=True, default='Global Organization', max_length=512)),
                ('status', models.CharField(db_index=True, default='completed', max_length=32)),
                ('overall_risk_score', models.FloatField(default=0.0)),
                ('risk_level', models.CharField(default='Informational', max_length=32)),
                ('grade', models.CharField(default='A', max_length=8)),
                ('total_findings', models.IntegerField(default=0)),
                ('severity_breakdown', models.JSONField(default=dict)),
                ('summary_data', models.JSONField(default=dict)),
                ('html_content', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('scan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reports', to='unified_scan.unifiedscanrecord')),
            ],
            options={
                'verbose_name': 'Security Report',
                'verbose_name_plural': 'Security Reports',
                'ordering': ['-created_at'],
            },
        ),
    ]
