# Generated by Django 5.1.15 on 2026-08-16 07:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('report_type', models.CharField(choices=[('EXECUTIVE', 'EXECUTIVE'), ('TECHNICAL', 'TECHNICAL'), ('NETWORK', 'NETWORK'), ('WEB', 'WEB'), ('API', 'API'), ('CODE', 'CODE')], max_length=20)),
                ('status', models.CharField(choices=[('READY', 'READY'), ('GENERATING', 'GENERATING'), ('FAILED', 'FAILED')], default='READY', max_length=20)),
                ('file', models.FileField(blank=True, null=True, upload_to='reports/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='projects.project')),
            ],
        ),
    ]
