# Generated by Django 5.1.15 on 2026-08-16 08:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='live_url',
            field=models.URLField(blank=True, default='', max_length=500),
        ),
        migrations.AddField(
            model_name='project',
            name='source_archive',
            field=models.FileField(blank=True, null=True, upload_to='source_archives/'),
        ),
        migrations.AddField(
            model_name='project',
            name='source_archive_name',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='project',
            name='source_archive_size',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='source_uploaded_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='Assessment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('live_url', models.URLField(blank=True, default='', max_length=500)),
                ('status', models.CharField(choices=[('DRAFT', 'DRAFT'), ('READY', 'READY'), ('QUEUED', 'QUEUED'), ('RUNNING', 'RUNNING'), ('COMPLETED', 'COMPLETED'), ('FAILED', 'FAILED'), ('CANCELLED', 'CANCELLED')], default='DRAFT', max_length=20)),
                ('selected_modules', models.JSONField(blank=True, default=list)),
                ('configuration', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assessments', to='projects.project')),
            ],
        ),
        migrations.CreateModel(
            name='AssessmentScope',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target_type', models.CharField(choices=[('LIVE_URL', 'LIVE_URL'), ('DOMAIN', 'DOMAIN'), ('IP', 'IP'), ('CIDR', 'CIDR'), ('API', 'API'), ('SOURCE_CODE', 'SOURCE_CODE')], max_length=20)),
                ('target', models.CharField(max_length=500)),
                ('included', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('assessment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scopes', to='projects.assessment')),
            ],
        ),
    ]
